### ISSUE TITLE
Specify sides from which to connect a node

### ISSUE THREAD

**Issue by monomon** [strathausen/dracula#19]
When creating node/edge specify sides on which to allow connections
(e.g. allow only north and south)
This is a bit specific, but it might be useful. It is a small change in graffle, will post a patch soon.
Let me know if you think it fits, though.

**Comment by strathausen** [comment]
You still have that patch? If it's small, I wouldn't mind... but the code base has changed a lot since then. Closing for now but feel free to re-open :-)

**Comment by monomon** [comment]
I do, in fact! Let me bring the code up to date and see if it works.
I ended up implementing that in a separate "overrides" file, which adds some functions on the Graph and Raphael prototypes, so I'll take some time to integrate it better and shape it up.

**Comment by monomon** [comment]
OK the required changes were more than I reckoned, but I might as well do it. Will just take a bit longer, but I get the chance to build my code around some new js fanciness.

**Comment by monomon** [comment]
Hey, I am still implementing the changes, but my test code is not working, so I'm trying to find out whether I'm missing something changed e.g. in layouts. Just wanted to let you know it's in progress.

**Comment by monomon** [comment]
I have created a pull request for this change https://github.com/strathausen/dracula/pull/45
