### ISSUE TITLE
Publish to Bower

### ISSUE THREAD

**Issue by CWSpear** [strathausen/dracula#30]
While you have a `bower.json` (which is half of the battle), it looks like you're not actually published on `bower`, which would be the other half.

The other other half is [knowing](https://www.youtube.com/watch?v=pele5vptVgc).

You can publish to `bower` via this command:

```
bower register graphdracula git://github.com/strathausen/dracula.git
```

It doesn't actually have to be *you* who does this, I could do it for you. But it seems like something intimate between a developer and his or her code, and I wouldn't want to do it without permission.

**Comment by strathausen** [comment]
Hey thanks, I've now published it to bower and it was actually that easy :) cheers!

**Comment by CWSpear** [comment]
Awesome, thanks!
