### ISSUE TITLE
TypeError: this.r.connection is not a function

### ISSUE THREAD

**Issue by Startouf** [strathausen/dracula#33]
I can't seem to draw any edge in my javascript. 
```
TypeError: this.r.connection is not a function
edge.connection = this.r.connection(edge.source.shape, edge.target.shape, edge.s...
    dracula_graph.js?body=1 (ligne 306, col. 24)
TypeError: this.r.connection is not a function
```

On the WEB I see many people using `r.connection` without any problem... yet the function is not defined. I tried downloading the latest version of Raphael, but it didn't help

**Comment by ruinpsilva** [comment]
I have the exact same issue! Have anybody found a solution for it?
Thanks

**Comment by ruinpsilva** [comment]
Got it! Load first raphael.js first than the others.

**Comment by strathausen** [comment]
I'll bundle it also.
