### ISSUE TITLE
Node labels that aren't IDs

### ISSUE THREAD

**Issue by keeganwitt** [strathausen/dracula#34]
I had an idea for an enhancement.  It'd be cool if we could specify a label for nodes that is different than the ID used to connect nodes with edges.  For backwards compatibility, if the node label isn't specified, the label could default to the ID.

**Comment by strathausen** [comment]
Working on that...

**Comment by strathausen** [comment]
Should actually work now :-) forgot to look at the issue... let me know if the latest version does what you need!
