### ISSUE TITLE
Algorithms export?

### ISSUE THREAD

**Issue by pazqo** [strathausen/dracula#36]
Hi there!

I was wondering why there is no export for Algorithms. I wanted to pass an ordering to the layout, but I noticed that 'graphdracula' modulo exports do not include any of the algorithms, so I need to compute it by hand, while there's a topologicalSort available.

Is this intentional?

**Comment by strathausen** [comment]
Thanks for reporting! You should now see OrderedTree, Spring and TournamentTree exported.
