### ISSUE TITLE
It seems like NPM package is incomplete

### ISSUE THREAD

**Issue by mfidemraizer** [strathausen/dracula#40]
I've installed `graphdracula` using `jspm` (i.e. `jspm install graphdracula`) and `/layout` JavaScript files aren't downloaded.

Thank you in advance!

**Comment by mfidemraizer** [comment]
Also, `/renderer` and `/algorithms` are empty.

**Comment by strathausen** [comment]
I see the files under `/lib/layout` etc., can you check? Can you tell me more about what you are trying to do? Thank you!

**Comment by mfidemraizer** [comment]
Finally your diagrams didn't fit well in my scenario and I've found another library. 

BTW, did you try to install the library using `jspm install npm:graphdracula` command?

**Comment by strathausen** [comment]
Yes, that's what I did.
