### ISSUE TITLE
Error on importing the library

### ISSUE THREAD

**Issue by strdr4605** [strathausen/dracula#53]
In got an error at 
```js
Raphael.fn.connection = function Connection(obj1, obj2, style) {
```
<img width="1668" alt="screen shot 2019-02-26 at 21 52 46" src="https://user-images.githubusercontent.com/16056918/53442075-11437780-3a11-11e9-9b1c-9316d3a94dd8.png">

**Comment by strathausen** [comment]
Did you include Raphaeljs before including dracula?

**Comment by strdr4605** [comment]
@strathausen
In this example, no, but included earlier but still got the error!
Can you show the right way?!

**Comment by strathausen** [comment]
You need to do it every time, also in this example! Just insert another `<script>` tag with Raphael in it. Also, the HTML seems to be only the script tag, better to have a complete HTML file! With `<head>`, `<body>` and everything.

You may also want to take look at the examples in the repository!

If you still have issues, let me know.
